### PR TITLE
Update desktop-enter-data-directly-into-desktop.md

### PR DESCRIPTION
**Pull request by unisong114**

### CODE REVIEW

**Comment by srvbpigh** [comment]
Hello, @unisong114:

Thank you for your contribution! We are processing your suggestions and we will update you shortly.  

Kind regards, 

Microsoft DOCS Global Experience Team

**Comment by srvbpigh** [comment]
Hello, @unisong114:

Thank you for your contribution.

Unfortunately, your feedback _has not been accepted_. Below you will find comments on the declined suggestions:

----------------------------º---------------------------- 
 **File: powerbi-docs/desktop-enter-data-directly-into-desktop.md** 

**Current version:** 
```
데이터를 직접 입력하려면 **홈** 리본에서 **데이터 입력**을 선택합니다.
```

**Requested change:** 
```
데이터를 직접 입력하려면 리본 메뉴 **홈** 탭에서 **데이터 입력**을 선택합니다.
```
**Decline reason:** English source is 'from the Home ribbon', and the current translation is correct.
----------------------------º---------------------------- 


We truly appreciate your contribution to our articles and we are looking forward to receiving your valuable feedback. Thank you for your time and support.

Microsoft DOCS Global Experience Team

**Comment by unisong114** [comment]
Hello, team,

Thank you for your work.
There is one saying about the mail below.
I have done similar feedback several times such as below.
https://github.com/MicrosoftDocs/powerbi-docs.ko-kr/pull/201/commits/ef431073bac959b0a03762bfcabe2c17eefcfe81

That feedback was accepted but this case is not.
I think that the contents should be modified like other cases.
I want to hear your opinion.

Thank you.

**Comment by v-radelg** [comment]
Hi @unisong114 thank you for your message

We will contact our moderator to re evaluate your suggestion

Kind regards,

Microsoft DOCS Global Experience Team

**Comment by v-radelg** [comment]
Hi @unisong114 

Our linguistic team have re-evaluated your suggestions and since they consider the change to be preferential, they decided to reject the suggestions in order to keep the global consistency.


We   truly appreciate your contribution to our articles and we are looking forward   to receiving your valuable feedback. Thank you for your time and support.

Microsoft   DOCS Global Experience Team

**Pull request closed without merging**
